### ISSUE TITLE
Fujitsu driver option support

### ISSUE THREAD

**Issue by IBMPortablePc** [rocketraman/sane-scan-pdf#9] opened 2020-07-19 03:06 UTC
Thank you for a great script. GUI is well and good, however CLI is often the way to simply get things done. A case in point is the lack of a decent Mac frontend for Sane.

I had no trouble using this script on my Mac (OS X 10.14.3) , once I installed the dependencies in Brew. In order to install scanadf I had to compile the Sane frontends, however this went smoothly.

However, the Fujitsu driver ( for my Scansnap S510M) supports brightness and contrast (see https://fossies.org/dox/sane-backends-1.0.27/fujitsu_8c_source.html etc) and I suspect that I can use those option by tweaking your script?

Also, I find the cropping to be a little too random i.e. sometimes it is too aggressive, however I guess that's simply how the driver works.

Lastly, the OCR option works perfectly except that the resulting PDF is extremely large i.e. A0 or A1 in size even if the original is A5. Any thoughts on this would be appreciated although I suspect it's an issue with how one of the dependencies works on Macs.

**Comment by IBMPortablePc** [comment] 2020-07-19 06:53
Okay, upon further examination I see that PS2PDF is performing the cropping, despite it being a feature of the driver. Now to work out how to use the driver cropping and not ps2pdf.....

**Comment by rocketraman** [comment] 2020-07-19 12:04
> Thank you for a great script.

I'm happy people are finding it useful.

> I had no trouble using this script on my Mac (OS X 10.14.3) , once I installed the dependencies in Brew. In order to install scanadf I had to compile the Sane frontends, however this went smoothly.

Nice to hear.

> However, the Fujitsu driver ( for my Scansnap S510M) supports brightness and contrast (see https://fossies.org/dox/sane-backends-1.0.27/fujitsu_8c_source.html etc) and I suspect that I can use those option by tweaking your script?

Yes, that should be quite easy to add. I might also add a way to "pass through" options to the driver.

> Lastly, the OCR option works perfectly except that the resulting PDF is extremely large i.e. A0 or A1 in size even if the original is A5. Any thoughts on this would be appreciated although I suspect it's an issue with how one of the dependencies works on Macs.

When using ocr, tesseract does the conversion into PDF. Does this size issue happen consistently? What version of tesseract do you have installed?

> Okay, upon further examination I see that PS2PDF is performing the cropping, despite it being a feature of the Fujitsu driver. Now to work out how to use the driver cropping and not ps2pdf.....

The `--crop` option actually does set the Fujitsu driver `--sw-crop=yes` option. It then asks `ps2pdf` to respect the bounding box in the Postscript data. I actually can't remember why I added this, or if this is a bug, but if you think this is the problem try commenting out this line, and see what happens:

https://github.com/rocketraman/sane-scan-pdf/blob/master/scan#L188

> Also, I find the cropping to be a little too random i.e. sometimes it is too aggressive, however I guess that's simply how the driver works.

You could try commenting out the deletion of the intermediate outputs as mentioned here https://github.com/rocketraman/sane-scan-pdf/issues/8#issuecomment-658198491 and try and determine where in the pipeline the issue is occurring. If it turns out the aggressive crop is as result of a post-scan stage (like ps2pdf), then post the intermediate outputs somewhere (send them to me privately if you wish) and I can take a look.

**Comment by rocketraman** [comment] 2020-07-19 12:24
Check out the code in branch `issue-9` -- it should allow you to pass through any driver option you like with `-xo` (short for eXtended option). For example:

```
scan -xo "--brightness 50 --contrast -10" -o scan.pdf
```

**Comment by rocketraman** [comment] 2020-07-19 12:37
> The --crop option actually does set the Fujitsu driver --sw-crop=yes option. It then asks ps2pdf to respect the bounding box in the Postscript data. I actually can't remember why I added this, or if this is a bug.

Just tried it, and it isn't a bug -- its necessary to get the PDF to respect the size of driver image output.

**Comment by rocketraman** [comment] 2020-07-19 12:42
In my local testing, I do notice that tesseract (with the `--ocr` option) does a slightly poorer job at setting the bounding box correctly, and does crop a bit beyond what the driver has output. If you were using the `--ocr` option with `--crop`, can you try it without `--ocr`?

**Comment by IBMPortablePc** [comment] 2020-07-21 00:30
Tesseract creating very large PDF page sizes is  a known issue, with a suggested solution.

"Set the dpi of the input images. Use mogrify from ImageMagick or similar."
https://github.com/tesseract-ocr/tesseract/issues/150

I have noticed that my cropping issue is that sometimes scans are cropped to exactly Letter size, even if they are A4 and A4 is specified. IT appears that there is a page size setting somewhere that I am overlooking, although I do not know why I sometimes do end up with A4 pdfs (assuming I don't use OCR/tesseract).

**Comment by rocketraman** [comment] 2020-07-27 14:50
> Tesseract creating very large PDF page sizes is a known issue, with a suggested solution:
> 
> "Set the dpi of the input images. Use mogrify from ImageMagick or similar."
> [tesseract-ocr/tesseract#150](https://github.com/tesseract-ocr/tesseract/issues/150)

Thanks for the link, I'll take a look.

> I have noticed that my cropping issue is that sometimes scans are cropped to exactly Letter size, even if they are A4 and A4 is specified. IT appears that there is a page size setting somewhere that I am overlooking, although I do not know why I sometimes do end up with A4 pdfs (assuming I don't use OCR/tesseract).

Its possible you are running into https://github.com/rocketraman/sane-scan-pdf/issues/8.

**Comment by rocketraman** [comment] 2020-07-29 21:21
I've merged the extended option support into `master`, closing. I will re-open a separate issue for the tesseract problem once I look into it.

**Closed by rocketraman** 2020-07-29 21:21 UTC
